# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArtNetConfigMessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41rtNetConfigMessages.proto\x12\x11ola.plugin.artnet\"T\n\x0eOptionsRequest\x12\x12\n\nshort_name\x18\x01 \x01(\t\x12\x11\n\tlong_name\x18\x02 \x01(\t\x12\x0e\n\x06subnet\x18\x03 \x01(\x05\x12\x0b\n\x03net\x18\x04 \x01(\x05\"b\n\x0cOptionsReply\x12\x0e\n\x06status\x18\x01 \x02(\r\x12\x12\n\nshort_name\x18\x02 \x02(\t\x12\x11\n\tlong_name\x18\x03 \x02(\t\x12\x0e\n\x06subnet\x18\x04 \x02(\x05\x12\x0b\n\x03net\x18\x05 \x02(\x05\"#\n\x0fNodeListRequest\x12\x10\n\x08universe\x18\x01 \x02(\x05\" \n\nOutputNode\x12\x12\n\nip_address\x18\x01 \x02(\r\"<\n\rNodeListReply\x12+\n\x04node\x18\x01 \x03(\x0b\x32\x1d.ola.plugin.artnet.OutputNode\"\xf3\x01\n\x07Request\x12\x34\n\x04type\x18\x01 \x02(\x0e\x32&.ola.plugin.artnet.Request.RequestType\x12\x32\n\x07options\x18\x02 \x01(\x0b\x32!.ola.plugin.artnet.OptionsRequest\x12\x35\n\tnode_list\x18\x03 \x01(\x0b\x32\".ola.plugin.artnet.NodeListRequest\"G\n\x0bRequestType\x12\x1a\n\x16\x41RTNET_OPTIONS_REQUEST\x10\x01\x12\x1c\n\x18\x41RTNET_NODE_LIST_REQUEST\x10\x02\"\xe3\x01\n\x05Reply\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\".ola.plugin.artnet.Reply.ReplyType\x12\x30\n\x07options\x18\x02 \x01(\x0b\x32\x1f.ola.plugin.artnet.OptionsReply\x12\x33\n\tnode_list\x18\x03 \x01(\x0b\x32 .ola.plugin.artnet.NodeListReply\"A\n\tReplyType\x12\x18\n\x14\x41RTNET_OPTIONS_REPLY\x10\x01\x12\x1a\n\x16\x41RTNET_NODE_LIST_REPLY\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ArtNetConfigMessages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIONSREQUEST._serialized_start=49
  _OPTIONSREQUEST._serialized_end=133
  _OPTIONSREPLY._serialized_start=135
  _OPTIONSREPLY._serialized_end=233
  _NODELISTREQUEST._serialized_start=235
  _NODELISTREQUEST._serialized_end=270
  _OUTPUTNODE._serialized_start=272
  _OUTPUTNODE._serialized_end=304
  _NODELISTREPLY._serialized_start=306
  _NODELISTREPLY._serialized_end=366
  _REQUEST._serialized_start=369
  _REQUEST._serialized_end=612
  _REQUEST_REQUESTTYPE._serialized_start=541
  _REQUEST_REQUESTTYPE._serialized_end=612
  _REPLY._serialized_start=615
  _REPLY._serialized_end=842
  _REPLY_REPLYTYPE._serialized_start=777
  _REPLY_REPLYTYPE._serialized_end=842
# @@protoc_insertion_point(module_scope)
