# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UsbProConfigMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aUsbProConfigMessages.proto\x12\x11ola.plugin.usbpro\"m\n\x0eParameterReply\x12\x15\n\rfirmware_high\x18\x01 \x02(\r\x12\x10\n\x08\x66irmware\x18\x02 \x02(\r\x12\x12\n\nbreak_time\x18\x03 \x02(\r\x12\x10\n\x08mab_time\x18\x04 \x02(\r\x12\x0c\n\x04rate\x18\x05 \x02(\r\"W\n\x10ParameterRequest\x12\x0f\n\x07port_id\x18\x04 \x02(\r\x12\x12\n\nbreak_time\x18\x01 \x01(\r\x12\x10\n\x08mab_time\x18\x02 \x01(\r\x12\x0c\n\x04rate\x18\x03 \x01(\r\"#\n\x11SerialNumberReply\x12\x0e\n\x06serial\x18\x01 \x02(\t\"I\n\x13PortAssignmentReply\x12\x18\n\x10port_assignment1\x18\x01 \x02(\r\x12\x18\n\x10port_assignment2\x18\x02 \x02(\r\"\xe4\x01\n\x07Request\x12\x34\n\x04type\x18\x01 \x02(\x0e\x32&.ola.plugin.usbpro.Request.RequestType\x12\x37\n\nparameters\x18\x02 \x01(\x0b\x32#.ola.plugin.usbpro.ParameterRequest\"j\n\x0bRequestType\x12\x1c\n\x18USBPRO_PARAMETER_REQUEST\x10\x01\x12\x19\n\x15USBPRO_SERIAL_REQUEST\x10\x02\x12\"\n\x1eUSBPRO_PORT_ASSIGNMENT_REQUEST\x10\x03\"\xd2\x02\n\x05Reply\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\".ola.plugin.usbpro.Reply.ReplyType\x12\x35\n\nparameters\x18\x02 \x01(\x0b\x32!.ola.plugin.usbpro.ParameterReply\x12;\n\rserial_number\x18\x03 \x01(\x0b\x32$.ola.plugin.usbpro.SerialNumberReply\x12?\n\x0fport_assignment\x18\x04 \x01(\x0b\x32&.ola.plugin.usbpro.PortAssignmentReply\"b\n\tReplyType\x12\x1a\n\x16USBPRO_PARAMETER_REPLY\x10\x01\x12\x17\n\x13USBPRO_SERIAL_REPLY\x10\x02\x12 \n\x1cUSBPRO_PORT_ASSIGNMENT_REPLY\x10\x03')



_PARAMETERREPLY = DESCRIPTOR.message_types_by_name['ParameterReply']
_PARAMETERREQUEST = DESCRIPTOR.message_types_by_name['ParameterRequest']
_SERIALNUMBERREPLY = DESCRIPTOR.message_types_by_name['SerialNumberReply']
_PORTASSIGNMENTREPLY = DESCRIPTOR.message_types_by_name['PortAssignmentReply']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_REQUEST_REQUESTTYPE = _REQUEST.enum_types_by_name['RequestType']
_REPLY_REPLYTYPE = _REPLY.enum_types_by_name['ReplyType']
ParameterReply = _reflection.GeneratedProtocolMessageType('ParameterReply', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERREPLY,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.ParameterReply)
  })
_sym_db.RegisterMessage(ParameterReply)

ParameterRequest = _reflection.GeneratedProtocolMessageType('ParameterRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERREQUEST,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.ParameterRequest)
  })
_sym_db.RegisterMessage(ParameterRequest)

SerialNumberReply = _reflection.GeneratedProtocolMessageType('SerialNumberReply', (_message.Message,), {
  'DESCRIPTOR' : _SERIALNUMBERREPLY,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.SerialNumberReply)
  })
_sym_db.RegisterMessage(SerialNumberReply)

PortAssignmentReply = _reflection.GeneratedProtocolMessageType('PortAssignmentReply', (_message.Message,), {
  'DESCRIPTOR' : _PORTASSIGNMENTREPLY,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.PortAssignmentReply)
  })
_sym_db.RegisterMessage(PortAssignmentReply)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.Reply)
  })
_sym_db.RegisterMessage(Reply)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARAMETERREPLY._serialized_start=49
  _PARAMETERREPLY._serialized_end=158
  _PARAMETERREQUEST._serialized_start=160
  _PARAMETERREQUEST._serialized_end=247
  _SERIALNUMBERREPLY._serialized_start=249
  _SERIALNUMBERREPLY._serialized_end=284
  _PORTASSIGNMENTREPLY._serialized_start=286
  _PORTASSIGNMENTREPLY._serialized_end=359
  _REQUEST._serialized_start=362
  _REQUEST._serialized_end=590
  _REQUEST_REQUESTTYPE._serialized_start=484
  _REQUEST_REQUESTTYPE._serialized_end=590
  _REPLY._serialized_start=593
  _REPLY._serialized_end=931
  _REPLY_REPLYTYPE._serialized_start=833
  _REPLY_REPLYTYPE._serialized_end=931
# @@protoc_insertion_point(module_scope)
