# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tRpc.proto\x12\x07ola.rpc\"S\n\nRpcMessage\x12\x1b\n\x04type\x18\x01 \x02(\x0e\x32\r.ola.rpc.Type\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x04 \x01(\x0c*\xd2\x01\n\x04Type\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\x13\n\x0fRESPONSE_CANCEL\x10\x03\x12\x13\n\x0fRESPONSE_FAILED\x10\x04\x12\x1c\n\x18RESPONSE_NOT_IMPLEMENTED\x10\x05\x12\x0e\n\nDISCONNECT\x10\x06\x12\x16\n\x12\x44\x45SCRIPTOR_REQUEST\x10\x07\x12\x17\n\x13\x44\x45SCRIPTOR_RESPONSE\x10\x08\x12\x12\n\x0eREQUEST_CANCEL\x10\t\x12\x12\n\x0eSTREAM_REQUEST\x10\n')

_TYPE = DESCRIPTOR.enum_types_by_name['Type']
Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
REQUEST = 1
RESPONSE = 2
RESPONSE_CANCEL = 3
RESPONSE_FAILED = 4
RESPONSE_NOT_IMPLEMENTED = 5
DISCONNECT = 6
DESCRIPTOR_REQUEST = 7
DESCRIPTOR_RESPONSE = 8
REQUEST_CANCEL = 9
STREAM_REQUEST = 10


_RPCMESSAGE = DESCRIPTOR.message_types_by_name['RpcMessage']
RpcMessage = _reflection.GeneratedProtocolMessageType('RpcMessage', (_message.Message,), {
  'DESCRIPTOR' : _RPCMESSAGE,
  '__module__' : 'Rpc_pb2'
  # @@protoc_insertion_point(class_scope:ola.rpc.RpcMessage)
  })
_sym_db.RegisterMessage(RpcMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPE._serialized_start=108
  _TYPE._serialized_end=318
  _RPCMESSAGE._serialized_start=22
  _RPCMESSAGE._serialized_end=105
# @@protoc_insertion_point(module_scope)
